ACHIEVEMENT_NAMES = {
    "openInventory": "Taking Inventory",
    "mineWood": "Getting Wood",
    "buildWorkBench": "Benchmarking",
    "buildPickaxe": "Time to Mine!",
    "buildFurnace": "Hot Topic",
    "acquireIron": "Acquire Hardware",
    "buildHoe": "Time to Farm!",
    "makeBread": "Bake Bread",
    "bakeCake": "The Lie",
    "buildBetterPickaxe": "Getting an Upgrade",
    "cookFish": "Delicious Fish",
    "onARail": "On A Rail",
    "buildSword": "Time to Strike!",
    "killEnemy": "Monster Hunter",
    "killCow": "Cow Tipper",
    "breedCow": "Repopulation",
    "flyPig": "When Pigs Fly",
    "snipeSkeleton": "Sniper Duel",
    "diamonds": "DIAMONDS!",
    "diamondsToYou": "Diamonds to you!",
    "portal": "We Need to Go Deeper",
    "ghast": "Return to Sender",
    "blazeRod": "Into Fire",
    "potion": "Local Brewery",
    "theEnd": "The End?",
    "theEnd2": "The End.",
    "spawnWither": "The Beginning?",
    "killWither": "The Beginning.",
    "fullBeacon": "Beaconator",
    "exploreAllBiomes": "Adventuring Time",
    "enchantments": "Enchanter",
    "overkill": "Overkill",
    "bookcase": "Librarian",
}

ENTITY_NAMES = {
    "Creeper": "Creeper",
    "Skeleton": "Skeleton",
    "Spider": "Spider",
    "Giant": "Giant",
    "Zombie": "Zombie",
    "Slime": "Slime",
    "Ghast": "Ghast",
    "PigZombie": "Zombie Pigman",
    "Enderman": "Enderman",
    "Silverfish": "Silverfish",
    "CaveSpider": "Cave Spider",
    "Blaze": "Blaze",
    "LavaSlime": "Magma Cube",
    "MushroomCow": "Mooshroom",
    "Villager": "Villager",
    "VillagerGolem": "Iron Golem",
    "SnowMan": "Snow Golem",
    "EnderDragon": "Ender Dragon",
    "WitherBoss": "Wither",
    "Witch": "Witch",
    "Pig": "Pig",
    "Sheep": "Sheep",
    "Cow": "Cow",
    "Chicken": "Chicken",
    "Squid": "Squid",
    "Wolf": "Wolf",
    "Ozelot": "Ocelot",
    "Cat": "Cat",
    "Bat": "Bat",
    "EntityHorse": "Horse",
    "horse": "Horse",
    "donkey": "Donkey",
    "mule": "Mule",
    "skeletonhorse": "Skeleton Horse",
    "zombiehorse": "Zombie Horse",
}
